### ISSUE TITLE
Output Filter Design and Simulation

### ISSUE THREAD

**Issue by alihashemi2002** [UCI-UAVForge/Avionics#12]
Design a Low-Pass Filter with a cutoff frequency of 500-600 kHz. Must be a LC filter. Refer to attached document for design guidance. Filter must be able to handle 3A of current with little to no voltage drop. This can be simulated by attached a known voltage source to the input of the filter and a known resistance shunted to the output to simulate a 3A load.  

Deliverable for this item: Calculations (in Mathematica preferably), Circuit Diagram (in Altium Designer), bode plot of the simulated frequency response (in LTSpice or PSPICE). 

Estimate time for this item: 2 Hours

[Filter Design.pdf](https://github.com/UCI-UAVForge/Avionics/files/11328/Filter.Design.pdf)

**Comment by steveocho** [comment]
Attached is the bode plot of the simulated frequency response done in LTSpice.
Let me know if there are any problems.

Inductor = 18 nH
Capacitor = 4.7 uF
Resistor = 4 Ohms
AC Amplitude = 1 V

![screenshot 49](https://cloud.githubusercontent.com/assets/15005167/10625850/912bf9e2-775d-11e5-8566-6ca9bf0ab0ba.png)

**Comment by alihashemi2002** [comment]
@steveocho the magnitude is in mdB. You have to redesign so that the cutoff frequency is 500-600kHz at -3dB!

**Comment by steveocho** [comment]
Alright I'll get get on that.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.4.10&pv=5.0.1&source=email_footer_2] On Fri, Oct 23, 2015 at 4:02 PM, Ali Hashemi < notifications@github.com [notifications@github.com] > wrote:
@steveocho [https://github.com/steveocho] the magnitude is in mdB. You have to redesign so that the cutoff frequency is
500-600kHz at -3dB!

—
Reply to this email directly or view it on GitHub
[https://github.com/UCI-UAVForge/Avionics/issues/12#issuecomment-150711937] .[https://github.com/notifications/beacon/AOT17zGpZ0EZGyotRoUhyMvFq88lX91Iks5o-rPrgaJpZM4GMpJR.gif]

**Comment by steveocho** [comment]
![screenshot 82](https://cloud.githubusercontent.com/assets/15005167/10927748/37e0cd72-8257-11e5-8997-a8246de157c0.png)

Can't upload .asc (LTSpice file type extension) so I just took a screenshot.

**Comment by alihashemi2002** [comment]
Simulation file will be uploaded to repo. Thanks
